### ISSUE TITLE
Hello Microverse Project - code review

### ISSUE THREAD

**Issue by devendra-alt** [devendra-alt/hello-microverse#1]
Added
-index.html
-style.css

Test Added
-github workflow (HTML+CSS linter)
-hintx

**Comment by bobb-Rob** [comment]
## STATUS: CHANGES REQUIRED ♻️
Hi @devendra-alt, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights

✅ Set up project very well with .gitignore file.

## Required Changes ♻️

- [ ] First, you are expected to submit a **_pull request_** and **_NOT_** an **_issue_** while requesting for project review. Follow [this link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request) to learn how to create a pull request. Kindly make the changes I will list below and then open a pull request and submit the link to the pull request.**_Please take note of your subsequent project while you are a student with Microverse._** 
- [ ] In your README file, I see issues: 
   - Remove this text `Microverse README Template` as it has nothing to do specifically with this project. 
   - All sections of this README template are mandatory except the FAQ which is optional.
   - For the Key Features section, kindly highlight what this project is all about. This will make it easy for those who go through this repository to know what was implemented by reading the README.md file. 👍
   - Since this project does not require any demo, you can leave out the Live Demo section.
   - For the Getting Started Section, and the Prerequisite Section, kindly add tools that are needed before you can clone this repository on a local machine. Tools like:
        - Installation of Git
        - Installation of NPM
        - A working browser
        - Internet connection
        - A code editor like Visual Studio Code
        - Installation of Live Server plugging in Visual Studio Code
        - Any other tool you can think about
   - For the Setup section, kindly add instructions for cloning your repository on a local machine 👍
   - For the Install section, kindly add instructions for setting up linters used in this project
   - For the Usage section, include instructions for opening this project on a browser. For example, opening the project by launching the Live Server plugging in visual studio code or any other means that you know.
   - For future features, add at least things you will do in the future to improve this project.
   - For the MIT section, kindly add a valid LICENSE. You can follow the instructions on the right side of the article attached below to set up a valid LICENSE - https://choosealicense.com/licenses/mit/
   - Please ensure that you add a link to this issue in the pull request summary/description you will submit for the next review. 

Kindly implement all the changes listed above. It will make your README.md file look professional and it will give you an idea of how to set README.md files for most of the projects you will execute as a Microverse student. 👍 �

Cheers and Happy coding!👏👏👏

**Comment by devendra-alt** [comment]
Thank you for your feedback! I am looking forward to the changes
